namespace Taskify.Api.Models;

/// <summary>The kind of event a notification represents.</summary>
public enum NotificationType
{
    TaskAssigned = 1,
    TaskStatusChanged = 2,
    TaskCommented = 3
}

/// <summary>An in-app event record generated by the API.</summary>
public class Notification
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public NotificationType Type { get; set; }
    public string Message { get; set; } = string.Empty;
    public Guid? TaskId { get; set; }
    public Guid? ProjectId { get; set; }
    public bool IsRead { get; set; }
    public DateTimeOffset CreatedAt { get; set; }

    public User? User { get; set; }
}
